### ISSUE TITLE
Versioned releases for Jasmine v2?

### ISSUE THREAD

**Issue by michaelhogg** [avrelian/jasmine-custom-message#10]
Firstly, many thanks @avrelian for this great library :grinning:

The [`jasmine-2-0`](https://github.com/avrelian/jasmine-custom-message/tree/jasmine-2-0) branch was [created](https://github.com/avrelian/jasmine-custom-message/commit/2dc6801) in January 2014.

Since then, there have been 9 versioned releases on the [`master`](https://github.com/avrelian/jasmine-custom-message/tree/master) branch ([0.5.1](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.5.1), [0.5.2](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.5.2), [0.5.3](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.5.3), [0.6.0](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.6.0), [0.6.1](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.6.1), [0.7.0](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.7.0), [0.7.1](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.7.1), [0.7.2](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.7.2), [0.7.3](https://github.com/avrelian/jasmine-custom-message/releases/tag/v0.7.3)) for Jasmine v1.

But there haven't yet been any versioned releases on the `jasmine-2-0` branch for Jasmine v2.

[Jasmine 1.3.1](https://github.com/jasmine/jasmine/releases/tag/v1.3.1) (the final 1.x version) was released in December 2012, and [Jasmine 2.0.0](https://github.com/jasmine/jasmine/releases/tag/v2.0.0) was released in December 2013, so I guess the majority of Jasmine users are now using v2 and only a few people are still using v1.

So my questions are:

  * What are your plans for future releases?
  * Will you continue making releases on the `master` branch for Jasmine v1?
  * Will you start making releases on the `jasmine-2-0` branch for Jasmine v2 soon?

It would be nice to be able to install a Jasmine v2 compatible release using NPM with something like this in a `package.json` file:

    "jasmine-custom-message": "~0.8"

instead of:

    "jasmine-custom-message": "avrelian/jasmine-custom-message#jasmine-2-0"

Many thanks!

**Comment by avrelian** [comment]
You are welcome, Michael :))

And, of course, you are right. It's my fault that version of `jasmine-2-0` branch is still 0.1.0. It should coincide with `master` branch.

As for future plans. I am going to move `jasmine-2-0` branch into it's own repository (`jasmine2-custom-message`) and support the current repository till the end of `jasmine-1-3` support.
It will greatly improve usability, since one can simply use
```
"jasmine2-custom-message": "~0.8"
```
and 
```
npm install jasmine2-custom-message
```

Thank you for your help and interest.

**Comment by michaelhogg** [comment]
Many thanks for your quick reply :)

That sounds like a great plan :+1: I'm looking forward to the launch of your new [`jasmine2-custom-message`](https://github.com/avrelian/jasmine2-custom-message) repo!

**Comment by avrelian** [comment]
Done. See [jasmine2-custom-message](https://github.com/avrelian/jasmine2-custom-message).

**Comment by michaelhogg** [comment]
Awesome :grinning:

I noticed you also [created a spec](https://github.com/avrelian/jasmine2-custom-message/commit/ae0f540) for the new [format string](https://github.com/avrelian/jasmine-custom-message/pull/9) functionality – great!

Thanks so much for all your work on creating and maintaining this library :sunny:
