### ISSUE TITLE
does not work 

### ISSUE THREAD

**Issue by SET001** [avrelian/jasmine-custom-message#6]
Trying to use in jasmine with protractor:

```
   since("Asdasds").expect(1).toBe(2);
```
but still got regular error message:

```
1) Navigation Bar as Designer all buttons should exist in DOM
  Message:
    Expected 1 to be 2.
  Stack:
    Error: Failed expectation
```

my environment:
```
set@set:~/www/softline/wab/autoTests$ npm list | grep "jasmine"
├─┬ grunt-contrib-jasmine@0.8.2
│ ├── jasmine-core@2.2.0
├── jasmine-custom-message@0.7.2
set@set:~/www/softline/wab/autoTests$ npm ls | grep jasmine-custom-message
├── jasmine-custom-message@0.7.2
set@set:~/www/softline/wab/autoTests$ protractor --version
Version 1.6.1
set@set:~/www/softline/wab/autoTests$ 
```

**Comment by avrelian** [comment]
Ok. Let me check it.

**Comment by SET001** [comment]
@avrelian, Did you manage to reproduce this?

**Comment by avrelian** [comment]
No. My tests are passing, so it could be protractor-specific problem. I have no time to dive into Protractor. Could you help me in finding the reason?

**Comment by SET001** [comment]
I have no idea how can I help and how the reason can be found. Maybe you have some ideas on this?

**Comment by mikeycgto** [comment]
I can confirm this library does not work when using jasmine with protractor

**Comment by mikeycgto** [comment]
Probably has something to do with this here: https://github.com/angular/protractor/blob/master/lib/frameworks/jasmine2.js

**Comment by avrelian** [comment]
Thank you for the confirmation, Michael. I'll fix it ASAP, if it could be fixed.

**Comment by avrelian** [comment]
My specs with protractor are passing with no additional work on my side for jasmine1.3. For jasmine2.0  my specs are failing, so I need explicitly specify what version of framework I intend to use.
Michael, Konstantin, please specify version of framework in protractor configuration file 
```exports.config = {framework: 'jasmine2'}``` 
and let me know guys if it works. Otherwise, please reopen the issue.
