### ISSUE TITLE
Custom message not displayed when argument to 'expect' is a promise

### ISSUE THREAD

**Issue by jas13** [avrelian/jasmine-custom-message#7]
If the argument to `expect` is a promise such as `repeaterRows.count()` the custom message will not be displayed.

For example:
```
since('the number of displayed rows should match the number of expected rows').
expect(repeaterRows.count()).toBe(expectedRows.length);
```
will not display the custom message on failure.

This seems to be due to the promise not being resolved when the expectation is called because explicitly resolving it with `then()` seems to work:
```
var customExpect = function(message, actualPromise, expectedValue, matcher) {
    actualPromise.then(function(actualValue) {
        since(function(expected) {          
            message = message.replace('#actual', this.actual);
            message = message.replace('#expected', expected);
            return message;
        }).expect(actualValue)[matcher](expectedValue);
    });
};
```

**Comment by avrelian** [comment]
What library for a promise you are using?

**Comment by jas13** [comment]
I'm using protractor so ... WebDriver?

**Comment by jas13** [comment]
This is the promise library that webdriver uses: https://github.com/kriskowal/q

**Comment by avrelian** [comment]
Sorry for the late answer.

So, the problem has the following cause. `Jasmine` library does not support promises out of the box. To overcome this shortcoming Webdriver-Jasmine connector `jasminewd` in case of a promise wraps every matcher by it's promise variant, stores them all in a special object (let us call it `fake assertion object`) and returns it as a result of `global.expect` function instead of a raw `jasmine` assertion object.

```
// excerpt from .../protractor/node_modules/jasminewd/index.js
global.expect = function(actual) {
  if (actual instanceof webdriver.WebElement) {
    throw 'expect called with WebElement argument, expected a Promise. ' +
        'Did you mean to use .getText()?';
  }
  if (webdriver.promise.isPromise(actual)) {
    return promiseMatchers(actual);
  } else {
    return originalExpect(actual);
  }
};
```

Even worse for us, `jasminewd` drops this fake assertion object when the promise is resolved and creates a raw jasmine assertion object instead. 
```
// excerpt from .../protractor/node_modules/jasminewd/index.js
actualPromise.then(function(actual) {
  // ...
  var expectation = originalExpect(actual);
```

So, we lose the only connection between our custom message stored in the fake jasmine object and this raw jasmine assertion.

**Comment by avrelian** [comment]
The worst of all, the problem could not be solved on my end. Some editings is needed in `jasminewd` index.js file.

First of all, each promise matcher wrapper should be provided by fake assertion object.
```
function promiseMatchers(actualPromise) {
// ...
  promises[matcher] = wrapMatcher(matcher, actualPromise, false, promises);
  promises.not[matcher] = wrapMatcher(matcher, actualPromise, true, promises);
// ...
```

And when the promise is resolved a newly created raw jasmine object should get `actual` value and `message` property from the fake assertion object.

```
function wrapMatcher(matcher, actualPromise, not, promises) {
  //...
  actualPromise.then(function(actual) {
    //...
    var expectation = originalExpect(actual);
    expectation.actual = actual;
    expectation.message = promises.message;
```

**Comment by avrelian** [comment]
I doubt that these highly specific editings could ever be accepted by owner of `jasminewd`.

**Comment by avrelian** [comment]
Of course, there is a `brute force` way. We can wrap and redefine some `jasminewd` methods and functions in `onPrepare` method of the `protractor` config object. But I think that would be overkill.

**Comment by avrelian** [comment]
Any thoughts? Workarounds?

**Comment by jas13** [comment]
The `customExpect` function in my original post has been working fine for me as a workaround. So a failure from
```
customExpect('the number of displayed rows (#actual) should match the number of expected rows (#expected)', repeaterRows.count(), expectedRows.length, 'toBe');
```
will display (supposing an actual value of 4 and an expected value of 3)
```
'the number of displayed rows (4) should match the number of expected rows (3)'
```

**Comment by avrelian** [comment]
So, for promise you are using `customExpect` and for rest something else, aren't you?  If I got that right, it possibly can complicate workflow. From the very beginning I have strived for simplicity and straightforwardness. One can comment `since` function and `expect` function will work without a hassle.
```
describe('test', function() {
  it('should be ok', function() {
    //since('bla-bla-bla')
    expect(3).toEqual(4); // => ordinary jasmine message
  });
});
```

Could you please give me some examples of your specs.

**Comment by jas13** [comment]
The example you gave above is very specific and would only work for one specific case. I have a function that verifies _any_ table data:
```function(tableRows, expectedData)```
where `tableRows` is a protractor `ElementArrayFinder` and `expectedData` is an array of arrays containing the expected value for each cell. I use this for a number of different sized tables so using literal values won't work; the values have to be obtained through promises and variables.
